class Config:
    ROWS = 20
    COLS = 10

    COLOR_BLACK = 2
    COLOR_GREEN = 1

    EMPTY_CELL_ICON = " ·"

    PIECE_SPEED = 0.25
    FAST_PIECE_SPEED = 0.1
    PIECE_SPEED_INCREMENT = 0.05

    RESET_TEXT_INTERVAL = 0.5
